import React from "react";
import SpaceElement from "./SpaceElement";
// import Space from "../Space";
import { Col, Container, Row } from "react-bootstrap";
import useSpaceProgress from "../store";
const SpaceCanvas = () => {
  const canvas = useSpaceProgress((state) => state.canvas);
  return (
    <>
      <Container fluid className="home-section" id="home">
        <Container className="about-content">
          <Row>
            <Col md={12} className="heading" style={{ textAlign: "center" }}>
              <h1
                style={{
                  fontSize: "1.5rem",
                  fontWeight: "600",
                  letterSpacing: "0.5rem",
                }}
              >
                ABOUT US
              </h1>
              <div className="space">
                <p>Hello Fuddi</p>
                <svg
                  viewBox="0 0 1920 1080"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  style={{ transform: "scale(1.3)" }}
                >
                  <g clipPath="url(#clip0_401_2)">
                    <rect width="1920" height="1080" fill="#fffff" />
                    {/* <g opacity="0.3" filter="url(#filter0_f_401_2)">
                      <circle cx="-78" cy="1274" r="730" fill="#A22CBF" />
                    </g>
                    <g opacity="0.4" filter="url(#filter1_f_401_2)">
                      <path
                        d="M2332 553C2332 780.541 2147.54 965 1920 965C1692.46 965 1508 780.541 1508 553C1508 325.459 1692.46 141 1920 141C2147.54 141 2332 325.459 2332 553Z"
                        fill="#A22CBF"
                      />
                    </g> */}
                    {canvas.map((ele, idx) => {
                      return (
                        <SpaceElement
                          key={idx}
                          name={ele.name}
                          visibility={ele.visible}
                          neighbours={ele.neighbours}
                          element={ele.element}
                          quesNum={ele.qNo}
                          solved={ele.solved}
                        />
                      );
                    })}
                  </g>
                  <defs>
                    <filter
                      id="filter0_f_401_2"
                      x="-1208"
                      y="144"
                      width="2260"
                      height="2260"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                      />
                      <feGaussianBlur
                        stdDeviation="200"
                        result="effect1_foregroundBlur_401_2"
                      />
                    </filter>
                    <filter
                      id="filter1_f_401_2"
                      x="1108"
                      y="-259"
                      width="1624"
                      height="1624"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                      />
                      <feGaussianBlur
                        stdDeviation="200"
                        result="effect1_foregroundBlur_401_2"
                      />
                    </filter>
                    <filter
                      id="filter2_f_401_2"
                      x="194"
                      y="19"
                      width="1519"
                      height="77"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                      />
                      <feGaussianBlur
                        stdDeviation="2"
                        result="effect1_foregroundBlur_401_2"
                      />
                    </filter>
                    <filter
                      id="filter3_b_401_2"
                      x="712.415"
                      y="805.619"
                      width="166.171"
                      height="95.762"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter4_b_401_2"
                      x="354.226"
                      y="566.304"
                      width="154.242"
                      height="153.344"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter5_b_401_2"
                      x="311.854"
                      y="503.366"
                      width="196.113"
                      height="104.572"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter6_b_401_2"
                      x="400.05"
                      y="381.481"
                      width="107.115"
                      height="210.767"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter7_b_401_2"
                      x="465.928"
                      y="566.319"
                      width="68.5249"
                      height="208.507"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter8_b_401_2"
                      x="467.208"
                      y="538.196"
                      width="177.585"
                      height="70.1739"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter9_b_401_2"
                      x="540.156"
                      y="411.921"
                      width="105.688"
                      height="168.412"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter10_b_401_2"
                      x="540.012"
                      y="294.398"
                      width="57.9766"
                      height="160.392"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter11_b_401_2"
                      x="402.925"
                      y="232.481"
                      width="194.12"
                      height="102.492"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter12_b_401_2"
                      x="405.625"
                      y="165.715"
                      width="153.677"
                      height="110.122"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter13_b_401_2"
                      x="603.002"
                      y="539.586"
                      width="49.9951"
                      height="169.26"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter14_b_401_2"
                      x="611.143"
                      y="667.302"
                      width="132.622"
                      height="79.0366"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter15_b_401_2"
                      x="603.641"
                      y="474.897"
                      width="132.718"
                      height="106"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter16_b_401_2"
                      x="694"
                      y="354.078"
                      width="44.0005"
                      height="162.062"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter17_b_401_2"
                      x="847"
                      y="352.565"
                      width="44.0005"
                      height="162.062"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter18_b_401_2"
                      x="695.56"
                      y="289.381"
                      width="120.88"
                      height="105.878"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter19_b_401_2"
                      x="775.524"
                      y="288.402"
                      width="114.951"
                      height="104.81"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter20_b_401_2"
                      x="695.48"
                      y="472.61"
                      width="193.04"
                      height="45.0169"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter21_b_401_2"
                      x="785.294"
                      y="473.217"
                      width="104.411"
                      height="125.497"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter22_b_401_2"
                      x="785.726"
                      y="553.511"
                      width="118.548"
                      height="88.9639"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter23_b_401_2"
                      x="843.047"
                      y="600.815"
                      width="61.9053"
                      height="114.375"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter24_b_401_2"
                      x="847.885"
                      y="402.142"
                      width="198.23"
                      height="113.336"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter25_b_401_2"
                      x="848.008"
                      y="472.693"
                      width="162.984"
                      height="85.194"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter26_b_401_2"
                      x="969.067"
                      y="403.066"
                      width="77.8652"
                      height="153.848"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter27_b_401_2"
                      x="970.205"
                      y="474.656"
                      width="241.591"
                      height="83.2842"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter28_b_401_2"
                      x="1004.9"
                      y="402.136"
                      width="207.202"
                      height="115.366"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter29_b_401_2"
                      x="1170.38"
                      y="475.128"
                      width="187.237"
                      height="204.378"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter30_b_401_2"
                      x="1315.01"
                      y="526.353"
                      width="57.9727"
                      height="150.34"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter31_b_401_2"
                      x="1427.62"
                      y="346.426"
                      width="189.841"
                      height="210.854"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter32_b_401_2"
                      x="1466.04"
                      y="515.042"
                      width="150.917"
                      height="78.1565"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter33_b_401_2"
                      x="1330.07"
                      y="356.747"
                      width="109.573"
                      height="209.983"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter34_b_401_2"
                      x="1331.22"
                      y="525.082"
                      width="174.555"
                      height="68.1625"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter35_b_401_2"
                      x="1417.4"
                      y="361.874"
                      width="90.7285"
                      height="230.209"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter36_b_401_2"
                      x="1167.22"
                      y="606.776"
                      width="189.559"
                      height="71.1875"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter37_b_401_2"
                      x="1315.94"
                      y="637.115"
                      width="282.118"
                      height="139.607"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter38_b_401_2"
                      x="1037.47"
                      y="637.598"
                      width="319.068"
                      height="148.803"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter39_b_401_2"
                      x="828.435"
                      y="657.622"
                      width="197.13"
                      height="198.441"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter40_b_401_2"
                      x="1035.97"
                      y="740.986"
                      width="231.058"
                      height="114.416"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <filter
                      id="filter41_b_401_2"
                      x="835.516"
                      y="737.58"
                      width="248.969"
                      height="113.839"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="10"
                      />
                      <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_backgroundBlur_401_2"
                      />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_backgroundBlur_401_2"
                        result="shape"
                      />
                    </filter>
                    <clipPath id="clip0_401_2">
                      <rect width="1920" height="1080" fill="white" />
                    </clipPath>
                    <clipPath id="clip1_401_2">
                      <rect
                        width="32.9792"
                        height="33.776"
                        fill="white"
                        transform="translate(799.888 559.359)"
                      />
                    </clipPath>
                    <clipPath id="clip2_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(472.57 573.364)"
                      />
                    </clipPath>
                    <clipPath id="clip3_401_2">
                      <rect
                        width="37.1015"
                        height="37.0712"
                        fill="white"
                        transform="translate(714.967 860.872)"
                      />
                    </clipPath>
                    <clipPath id="clip4_401_2">
                      <rect
                        width="38.7505"
                        height="38.7188"
                        fill="white"
                        transform="translate(1244.28 822.153)"
                      />
                    </clipPath>
                    <clipPath id="clip5_401_2">
                      <rect
                        width="41.2239"
                        height="41.1902"
                        fill="white"
                        transform="translate(1573.25 742.244)"
                      />
                    </clipPath>
                    <clipPath id="clip6_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(868.32 604.669)"
                      />
                    </clipPath>
                    <clipPath id="clip7_401_2">
                      <rect
                        width="37.1015"
                        height="37.0712"
                        fill="white"
                        transform="translate(850.182 476.155)"
                      />
                    </clipPath>
                    <clipPath id="clip8_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(413.208 238.076)"
                      />
                    </clipPath>
                    <clipPath id="clip9_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(607.785 543.707)"
                      />
                    </clipPath>
                    <clipPath id="clip10_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(1154.41 605.492)"
                      />
                    </clipPath>
                    <clipPath id="clip11_401_2">
                      <rect
                        width="49.4687"
                        height="49.4282"
                        fill="white"
                        transform="translate(770.207 280.914)"
                      />
                    </clipPath>
                    <clipPath id="clip12_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(698.478 358.351)"
                      />
                    </clipPath>
                    <clipPath id="clip13_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(852.655 355.88)"
                      />
                    </clipPath>
                    <clipPath id="clip14_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(561.614 299.861)"
                      />
                    </clipPath>
                    <clipPath id="clip15_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(967.258 518.169)"
                      />
                    </clipPath>
                    <clipPath id="clip16_401_2">
                      <rect
                        width="65.9583"
                        height="65.9043"
                        fill="white"
                        transform="translate(990.343 388.832)"
                      />
                    </clipPath>
                    <clipPath id="clip17_401_2">
                      <rect
                        width="37.1015"
                        height="37.0712"
                        fill="white"
                        transform="translate(494.831 751.306)"
                      />
                    </clipPath>
                    <clipPath id="clip18_401_2">
                      <rect
                        width="37.1015"
                        height="37.0712"
                        fill="white"
                        transform="translate(722.387 718.354)"
                      />
                    </clipPath>
                    <clipPath id="clip19_401_2">
                      <rect
                        width="40"
                        height="39.9673"
                        fill="white"
                        transform="translate(400.016 375.651)"
                      />
                    </clipPath>
                    <clipPath id="clip20_401_2">
                      <rect
                        width="41.2239"
                        height="41.1902"
                        fill="white"
                        transform="translate(1168.43 476.979)"
                      />
                    </clipPath>
                    <clipPath id="clip21_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(1575.72 515.698)"
                      />
                    </clipPath>
                    <clipPath id="clip22_401_2">
                      <rect
                        width="32.9792"
                        height="32.9522"
                        fill="white"
                        transform="translate(545.125 411.898)"
                      />
                    </clipPath>
                    <clipPath id="clip23_401_2">
                      <rect
                        width="65.9583"
                        height="65.9043"
                        fill="white"
                        transform="translate(987.87 615.378)"
                      />
                    </clipPath>
                    <clipPath id="clip24_401_2">
                      <rect
                        width="49.4687"
                        height="49.4282"
                        fill="white"
                        transform="translate(1326.73 517.345)"
                      />
                    </clipPath>
                    <clipPath id="clip25_401_2">
                      <rect
                        width="41.2239"
                        height="41.1902"
                        fill="white"
                        transform="translate(1316.01 632.678)"
                      />
                    </clipPath>
                    <clipPath id="clip26_401_2">
                      <rect
                        width="41.2239"
                        height="41.1902"
                        fill="white"
                        transform="translate(1466.89 549.474)"
                      />
                    </clipPath>
                    <clipPath id="clip27_401_2">
                      <rect
                        width="41.2239"
                        height="41.1902"
                        fill="white"
                        transform="translate(834.517 806.501)"
                      />
                    </clipPath>
                    <clipPath id="clip28_401_2">
                      <rect
                        width="41.2239"
                        height="41.1902"
                        fill="white"
                        transform="translate(1041.46 738.125)"
                      />
                    </clipPath>
                    <clipPath id="clip29_401_2">
                      <rect
                        width="65"
                        height="65"
                        fill="white"
                        transform="translate(827 679)"
                      />
                    </clipPath>
                  </defs>
                </svg>
              </div>
            </Col>
          </Row>
        </Container>
      </Container>
    </>
  );
};

export default SpaceCanvas;
