
name: Deploy On Server

on:
  push:
    tags:
      - v*.*.*
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 16.17.0

    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy files via scp
      uses: appleboy/scp-action@master              
      with:
        key: ${{ secrets.SSHKEY }}
        source: "./build/"
        dest: ${{ secrets.DEST }}
        

    - name: Move files to correct place
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSHKEY }}
        source: "./build/"
        dest: ${{ secrets.DEST }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: scp -i $key -r $source $dest
        
